INSERT INTO trip_roles (name) VALUES ('OWNER') ON CONFLICT DO NOTHING;
INSERT INTO trip_roles (name) VALUES ('MANAGER') ON CONFLICT DO NOTHING;
INSERT INTO trip_roles (name) VALUES ('PARTICIPANT') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('USER') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('ADMIN') ON CONFLICT DO NOTHING;