spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  config:
    import: optional:secrets.yml
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
logging:
  level:
    org.springframework.security.web: DEBUG
server:
  error:
    include-message: always