INSERT INTO countries (name) VALUES ('Afganistan');
INSERT INTO countries (name) VALUES ('Albania');
INSERT INTO countries (name) VALUES ('Algieria');
INSERT INTO countries (name) VALUES ('Andora');
INSERT INTO countries (name) VALUES ('Angola');
INSERT INTO countries (name) VALUES ('Antigua i Barbuda');
INSERT INTO countries (name) VALUES ('Arabia Saudyjska');
INSERT INTO countries (name) VALUES ('Argentyna');
INSERT INTO countries (name) VALUES ('Armenia');
INSERT INTO countries (name) VALUES ('Australia');
INSERT INTO countries (name) VALUES ('Austria');
INSERT INTO countries (name) VALUES ('Azerbejdżan');
INSERT INTO countries (name) VALUES ('Bahamy');
INSERT INTO countries (name) VALUES ('Bahrajn');
INSERT INTO countries (name) VALUES ('Bangladesz');
INSERT INTO countries (name) VALUES ('Barbados');
INSERT INTO countries (name) VALUES ('Belgia');
INSERT INTO countries (name) VALUES ('Belize');
INSERT INTO countries (name) VALUES ('Benin');
INSERT INTO countries (name) VALUES ('Bhutan');
INSERT INTO countries (name) VALUES ('Białoruś');
INSERT INTO countries (name) VALUES ('Boliwia');
INSERT INTO countries (name) VALUES ('Bośnia i Hercegowina');
INSERT INTO countries (name) VALUES ('Botswana');
INSERT INTO countries (name) VALUES ('Brazylia');
INSERT INTO countries (name) VALUES ('Brunei');
INSERT INTO countries (name) VALUES ('Bułgaria');
INSERT INTO countries (name) VALUES ('Burkina Faso');
INSERT INTO countries (name) VALUES ('Burundi');
INSERT INTO countries (name) VALUES ('Chile');
INSERT INTO countries (name) VALUES ('Chiny');
INSERT INTO countries (name) VALUES ('Chorwacja');
INSERT INTO countries (name) VALUES ('Cypr');
INSERT INTO countries (name) VALUES ('Czad');
INSERT INTO countries (name) VALUES ('Czarnogóra');
INSERT INTO countries (name) VALUES ('Czechy');
INSERT INTO countries (name) VALUES ('Dania');
INSERT INTO countries (name) VALUES ('Demokratyczna Republika Konga');
INSERT INTO countries (name) VALUES ('Dominika');
INSERT INTO countries (name) VALUES ('Dominikana');
INSERT INTO countries (name) VALUES ('Dżibuti');
INSERT INTO countries (name) VALUES ('Egipt');
INSERT INTO countries (name) VALUES ('Ekwador');
INSERT INTO countries (name) VALUES ('Erytrea');
INSERT INTO countries (name) VALUES ('Estonia');
INSERT INTO countries (name) VALUES ('Eswatini');
INSERT INTO countries (name) VALUES ('Etiopia');
INSERT INTO countries (name) VALUES ('Fidżi');
INSERT INTO countries (name) VALUES ('Filipiny');
INSERT INTO countries (name) VALUES ('Finlandia');
INSERT INTO countries (name) VALUES ('Francja');
INSERT INTO countries (name) VALUES ('Gabon');
INSERT INTO countries (name) VALUES ('Gambia');
INSERT INTO countries (name) VALUES ('Ghana');
INSERT INTO countries (name) VALUES ('Grecja');
INSERT INTO countries (name) VALUES ('Grenada');
INSERT INTO countries (name) VALUES ('Gruzja');
INSERT INTO countries (name) VALUES ('Gujana');
INSERT INTO countries (name) VALUES ('Gwatemala');
INSERT INTO countries (name) VALUES ('Gwinea');
INSERT INTO countries (name) VALUES ('Gwinea Bissau');
INSERT INTO countries (name) VALUES ('Gwinea Równikowa');
INSERT INTO countries (name) VALUES ('Haiti');
INSERT INTO countries (name) VALUES ('Hiszpania');
INSERT INTO countries (name) VALUES ('Holandia');
INSERT INTO countries (name) VALUES ('Honduras');
INSERT INTO countries (name) VALUES ('Indie');
INSERT INTO countries (name) VALUES ('Indonezja');
INSERT INTO countries (name) VALUES ('Irak');
INSERT INTO countries (name) VALUES ('Iran');
INSERT INTO countries (name) VALUES ('Irlandia');
INSERT INTO countries (name) VALUES ('Islandia');
INSERT INTO countries (name) VALUES ('Izrael');
INSERT INTO countries (name) VALUES ('Jamajka');
INSERT INTO countries (name) VALUES ('Japonia');
INSERT INTO countries (name) VALUES ('Jemen');
INSERT INTO countries (name) VALUES ('Jordania');
INSERT INTO countries (name) VALUES ('Kambodża');
INSERT INTO countries (name) VALUES ('Kamerun');
INSERT INTO countries (name) VALUES ('Kanada');
INSERT INTO countries (name) VALUES ('Katar');
INSERT INTO countries (name) VALUES ('Kazachstan');
INSERT INTO countries (name) VALUES ('Kenia');
INSERT INTO countries (name) VALUES ('Kirgistan');
INSERT INTO countries (name) VALUES ('Kiribati');
INSERT INTO countries (name) VALUES ('Kolumbia');
INSERT INTO countries (name) VALUES ('Komory');
INSERT INTO countries (name) VALUES ('Kongo');
INSERT INTO countries (name) VALUES ('Korea Południowa');
INSERT INTO countries (name) VALUES ('Korea Północna');
INSERT INTO countries (name) VALUES ('Kostaryka');
INSERT INTO countries (name) VALUES ('Kuba');
INSERT INTO countries (name) VALUES ('Kuwejt');
INSERT INTO countries (name) VALUES ('Laos');
INSERT INTO countries (name) VALUES ('Lesotho');
INSERT INTO countries (name) VALUES ('Liban');
INSERT INTO countries (name) VALUES ('Liberia');
INSERT INTO countries (name) VALUES ('Libia');
INSERT INTO countries (name) VALUES ('Liechtenstein');
INSERT INTO countries (name) VALUES ('Litwa');
INSERT INTO countries (name) VALUES ('Luksemburg');
INSERT INTO countries (name) VALUES ('Łotwa');
INSERT INTO countries (name) VALUES ('Macedonia Północna');
INSERT INTO countries (name) VALUES ('Madagaskar');
INSERT INTO countries (name) VALUES ('Malawi');
INSERT INTO countries (name) VALUES ('Malediwy');
INSERT INTO countries (name) VALUES ('Malezja');
INSERT INTO countries (name) VALUES ('Mali');
INSERT INTO countries (name) VALUES ('Malta');
INSERT INTO countries (name) VALUES ('Maroko');
INSERT INTO countries (name) VALUES ('Mauretania');
INSERT INTO countries (name) VALUES ('Mauritius');
INSERT INTO countries (name) VALUES ('Meksyk');
INSERT INTO countries (name) VALUES ('Mikronezja');
INSERT INTO countries (name) VALUES ('Mjanma');
INSERT INTO countries (name) VALUES ('Mołdawia');
INSERT INTO countries (name) VALUES ('Monako');
INSERT INTO countries (name) VALUES ('Mongolia');
INSERT INTO countries (name) VALUES ('Mozambik');
INSERT INTO countries (name) VALUES ('Namibia');
INSERT INTO countries (name) VALUES ('Nauru');
INSERT INTO countries (name) VALUES ('Nepal');
INSERT INTO countries (name) VALUES ('Niemcy');
INSERT INTO countries (name) VALUES ('Niger');
INSERT INTO countries (name) VALUES ('Nigeria');
INSERT INTO countries (name) VALUES ('Nikaragua');
INSERT INTO countries (name) VALUES ('Norwegia');
INSERT INTO countries (name) VALUES ('Nowa Zelandia');
INSERT INTO countries (name) VALUES ('Oman');
INSERT INTO countries (name) VALUES ('Pakistan');
INSERT INTO countries (name) VALUES ('Palau');
INSERT INTO countries (name) VALUES ('Panama');
INSERT INTO countries (name) VALUES ('Papua-Nowa Gwinea');
INSERT INTO countries (name) VALUES ('Paragwaj');
INSERT INTO countries (name) VALUES ('Peru');
INSERT INTO countries (name) VALUES ('Polska');
INSERT INTO countries (name) VALUES ('Portugalia');
INSERT INTO countries (name) VALUES ('Republika Południowej Afryki');
INSERT INTO countries (name) VALUES ('Republika Środkowoafrykańska');
INSERT INTO countries (name) VALUES ('Republika Zielonego Przylądka');
INSERT INTO countries (name) VALUES ('Rosja');
INSERT INTO countries (name) VALUES ('Rumunia');
INSERT INTO countries (name) VALUES ('Rwanda');
INSERT INTO countries (name) VALUES ('Saint Kitts i Nevis');
INSERT INTO countries (name) VALUES ('Saint Lucia');
INSERT INTO countries (name) VALUES ('Saint Vincent i Grenadyny');
INSERT INTO countries (name) VALUES ('Salwador');
INSERT INTO countries (name) VALUES ('Samoa');
INSERT INTO countries (name) VALUES ('San Marino');
INSERT INTO countries (name) VALUES ('Senegal');
INSERT INTO countries (name) VALUES ('Serbia');
INSERT INTO countries (name) VALUES ('Seszele');
INSERT INTO countries (name) VALUES ('Sierra Leone');
INSERT INTO countries (name) VALUES ('Singapur');
INSERT INTO countries (name) VALUES ('Słowacja');
INSERT INTO countries (name) VALUES ('Słowenia');
INSERT INTO countries (name) VALUES ('Somalia');
INSERT INTO countries (name) VALUES ('Sri Lanka');
INSERT INTO countries (name) VALUES ('Stany Zjednoczone');
INSERT INTO countries (name) VALUES ('Suazi');
INSERT INTO countries (name) VALUES ('Sudan');
INSERT INTO countries (name) VALUES ('Sudan Południowy');
INSERT INTO countries (name) VALUES ('Surinam');
INSERT INTO countries (name) VALUES ('Syria');
INSERT INTO countries (name) VALUES ('Szwajcaria');
INSERT INTO countries (name) VALUES ('Szwecja');
INSERT INTO countries (name) VALUES ('Tadżykistan');
INSERT INTO countries (name) VALUES ('Tajlandia');
INSERT INTO countries (name) VALUES ('Tajwan');
INSERT INTO countries (name) VALUES ('Tanzania');
INSERT INTO countries (name) VALUES ('Timor Wschodni');
INSERT INTO countries (name) VALUES ('Togo');
INSERT INTO countries (name) VALUES ('Tonga');
INSERT INTO countries (name) VALUES ('Trynidad i Tobago');
INSERT INTO countries (name) VALUES ('Tunezja');
INSERT INTO countries (name) VALUES ('Turcja');
INSERT INTO countries (name) VALUES ('Turkmenistan');
INSERT INTO countries (name) VALUES ('Tuvalu');
INSERT INTO countries (name) VALUES ('Uganda');
INSERT INTO countries (name) VALUES ('Ukraina');
INSERT INTO countries (name) VALUES ('Urugwaj');
INSERT INTO countries (name) VALUES ('Uzbekistan');
INSERT INTO countries (name) VALUES ('Vanuatu');
INSERT INTO countries (name) VALUES ('Watykan');
INSERT INTO countries (name) VALUES ('Wenezuela');
INSERT INTO countries (name) VALUES ('Węgry');
INSERT INTO countries (name) VALUES ('Wielka Brytania');
INSERT INTO countries (name) VALUES ('Wietnam');
INSERT INTO countries (name) VALUES ('Włochy');
INSERT INTO countries (name) VALUES ('Wybrzeże Kości Słoniowej');
INSERT INTO countries (name) VALUES ('Wyspy Cooka');
INSERT INTO countries (name) VALUES ('Wyspy Marshalla');
INSERT INTO countries (name) VALUES ('Wyspy Salomona');
INSERT INTO countries (name) VALUES ('Wyspy Świętego Tomasza i Książęca');
INSERT INTO countries (name) VALUES ('Zambia');
INSERT INTO countries (name) VALUES ('Zimbabwe');