spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/soez_db
    username: root
    password: root

OPENAI_API_KEY : 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
OPENAI_API_URL: https://api.openai.com/v1/chat/completions