spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/soez_db
    username: root
    password: root

OPENAI_API_KEY: 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
OPENAI_API_URL: https://api.openai.com/v1/chat/completions

server:
  port: 8443
  ssl:
    key-store: classpath:server.p12
    key-store-password: soez12


weather:
  api:
    key: 47b5b2df22207f5b10070ff0835d9a84
    url: http://api.openweathermap.org/data/2.5/weather?q=