spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/soez_db
    username: root
    password: root
OPENAI_API_KEY : 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
OPENAI_API_URL: https://api.openai.com/v1/chat/completions
